nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        expose_headers: [ ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'Content-Type', 'Authorization','Preload', 'Fields', 'X-Custom-Auth','Origin','Access-Control-Allow-Origin', 'X-Requested-With', 'Content', 'Accept', 'X-LOCALE' ]
            allow_methods: [ 'POST', 'OPTIONS', 'PUT', 'PATCH', 'GET', 'DELETE' ]
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'OPTIONS', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
            hosts: [ '^api\.' ]
